### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by yassinMk** [VdoCipher/node-vdocipher#2]
In errors log I find this log
```
TypeError: Cannot read property 'statusCode' of undefined
     at Request._callback (/root/production/node_modules/vdocipher/lib/vdocipher.js:1:1319)
     at self.callback (/root/production/node_modules/request/request.js:188:22)
     at emitOne (events.js:77:13)
     at Request.emit (events.js:169:7)
     at Request.onRequestError (/root/production/node_modules/request/request.js:884:8)
     at emitOne (events.js:77:13)
     at ClientRequest.emit (events.js:169:7)
     at TLSSocket.socketErrorListener (_http_client.js:258:9)
     at emitOne (events.js:77:13)
     at TLSSocket.emit (events.js:169:7)
     at emitErrorNT (net.js:1256:8)
     at nextTickCallbackWith2Args (node.js:441:9)
     at process._tickDomainCallback (node.js:396:17)
```

**Comment by vibhavsinha** [comment]
`statusCode` is only used once in the code with `response.statusCode` . https://github.com/VdoCipher/node-vdocipher/blob/master/index.js#L38

I am not sure how [request](https://github.com/request/request) module provided undefined as the httpResponse object.

I have added a safety check which should correct this.

Please upgrade the [vdocipher](https://www.npmjs.com/package/vdocipher) package to latest version 1.2.5 .
